language: cpp
sudo: false
dist: xenial

os:
- linux

addons:
  apt:
    packages:
    - g++-5

git:
  submodules: false
branches:
  only:
  - master

script:
- cmake -D CMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage -fsanitize=address" ./
- make VERBOSE=1 -j 2
- ctest -VV

after_script:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info
- lcov --remove coverage.info '/usr/*' --output-file coverage.info
- lcov --list coverage.info
- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
